---
# This roles installs nodejs v6

- name: install make
  command: sudo yum install -y gcc-c++ make

- name: add nodesource repo
  shell: curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -

- name: install nodejs
  command: sudo yum install -y nodejs

- name: config
  shell: sudo npm config set registry https://registry.npm.taobao.org

- name: install gulp
  shell: sudo npm install --global gulp-cli
